### PR TITLE
Tidying and fixing

### PR DESCRIPTION
**Pull request by BaoHaiyah**

### CODE REVIEW

**Comment by tamxtanh** [comment]
private void shufflebtn_Click(object sender, RoutedEventArgs e)
        {
            shufflebtn.Foreground = (shufflebtn.Foreground != Brushes.DeepPink) ? Brushes.DeepPink : Brushes.White;
            shuffleMedia = (shuffleMedia == false && shufflebtn.Foreground == Brushes.DeepPink) ? true : false;           

            if (shuffleMedia)
            {
                subSongs.Clear();
                foreach (var song in songs)
                {
                    subSongs.Add(song);
                }
                subSongs.Shuffle();

                //
                for (int n = 0; n < subSongs.Count; n++)
                {
                    if (subSongs[n].path == songs[i].path)
                    {
                        i = n;
                        break;
                    }
                }
                //

               
                for (int i = 0; i < songMenu.Children.Count; i++)
                {
                    SongName songname = (SongName)songMenu.Children[i];
                    for (int j = 0; j < songs.Count; j++)
                    {
                        if (songname.Path == subSongs[j].path)
                        {
                            songname.IndexOfSong = j;
                            break;
                        }
                    }
                }
            }
            else
            {
                songMenu.Children.Clear();
                for (int i = 0; i < songs.Count; i++)
                {
                    Add_UcSongName(songs[i], i);
                }


                //
                for (int n = 0; n < songs.Count; n++)
                {
                    if (songs[n].path == subSongs[i].path)
                    {
                        i = n;
                        ActiveSongName(i);
                        break;
                    }
                }
                //  
            }
        }

**Comment by tamxtanh** [comment]
private void shufflebtn_Click(object sender, RoutedEventArgs e)
        {
            shufflebtn.Foreground = (shufflebtn.Foreground != Brushes.DeepPink) ? Brushes.DeepPink : Brushes.White;
            shuffleMedia = (shuffleMedia == false && shufflebtn.Foreground == Brushes.DeepPink) ? true : false;           

            if (shuffleMedia)
            {
                subSongs.Clear();
                foreach (var song in songs)
                {
                    subSongs.Add(song);
                }
                subSongs.Shuffle();

                //
                for (int n = 0; n < subSongs.Count; n++)
                {
                    if (subSongs[n].path == songs[i].path)
                    {
                        i = n;
                        break;
                    }
                }
                //

               
                for (int i = 0; i < songMenu.Children.Count; i++)
                {
                    SongName songname = (SongName)songMenu.Children[i];
                    for (int j = 0; j < songs.Count; j++)
                    {
                        if (songname.Path == subSongs[j].path)
                        {
                            songname.IndexOfSong = j;
                            break;
                        }
                    }
                }
            }
            else
            {
                songMenu.Children.Clear();
                for (int i = 0; i < songs.Count; i++)
                {
                    Add_UcSongName(songs[i], i);
                }


                //
                for (int n = 0; n < songs.Count; n++)
                {
                    if (songs[n].path == subSongs[i].path)
                    {
                        i = n;
                        ActiveSongName(i);
                        break;
                    }
                }
                //  
            }
        }

**Comment by tamxtanh** [comment]
Ông thử sửa cái click của nút Shuffle giống hàm này thử xem, tui thấy bên tui chạy ổn ấy.


        private void shufflebtn_Click(object sender, RoutedEventArgs e)
        {
            shufflebtn.Foreground = (shufflebtn.Foreground != Brushes.DeepPink) ? Brushes.DeepPink : Brushes.White;
            shuffleMedia = (shuffleMedia == false && shufflebtn.Foreground == Brushes.DeepPink) ? true : false;           

            if (shuffleMedia)
            {
                subSongs.Clear();
                foreach (var song in songs)
                {
                    subSongs.Add(song);
                }
                subSongs.Shuffle();

                //
                for (int n = 0; n < subSongs.Count; n++)
                {
                    if (subSongs[n].path == songs[i].path)
                    {
                        i = n;
                        break;
                    }
                }
                //

               
                for (int i = 0; i < songMenu.Children.Count; i++)
                {
                    SongName songname = (SongName)songMenu.Children[i];
                    for (int j = 0; j < songs.Count; j++)
                    {
                        if (songname.Path == subSongs[j].path)
                        {
                            songname.IndexOfSong = j;
                            break;
                        }
                    }
                }
            }
            else
            {
                songMenu.Children.Clear();
                for (int i = 0; i < songs.Count; i++)
                {
                    Add_UcSongName(songs[i], i);
                }


                //
                for (int n = 0; n < songs.Count; n++)
                {
                    if (songs[n].path == subSongs[i].path)
                    {
                        i = n;
                        ActiveSongName(i);
                        break;
                    }
                }
                //  
            }
        }

**Comment by BowJaro** [comment]
Huy đã check

**Review by BowJaro — APPROVED** [review]

**Pull request merged**
